"""empty message

Revision ID: 5ee4998a30a2
Revises: 
Create Date: 2024-01-26 21:45:01.048781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee4998a30a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('website', postgresql.ENUM('texnomart', 'mediapark', 'olcha', 'asaxiy', 'openshop', 'elmakon', 'discount', 'allgood', 'goodzone', 'radius', 'zon', 'ikarvon', 'eSavdo', 'idea', 'mytech', 'royaltech', 'elso', 'mago', 'macbro', 'azbo', 'maxcom', 'openshop_uz', 'brandstore', 'ultrashop', 'gshop', 'mycom', 'pcmarket', 'bozon', 'mionline', 'treetech', name='websites'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
